### ISSUE TITLE
vFense Windows Agent

### ISSUE THREAD

**Issue by jrosetto** [vFense/vFense#209]
After downloading and extracting the windows agent ip file I ran initial_setup.exe but keep getting the errpr 'failed attempting to download http://updater.toppatch.com/*' for every file.  Is there an alternative repo I can point to to get this working?

Thanks.

**Comment by ahbit** [comment]
Hi Jrosetto,

You need to recompile/compile the application :)

Thanks;
Andrew

**Comment by jrosetto** [comment]
Thanks for the response.  Feeling like a n00b :)

**Comment by jrosetto** [comment]
I see in the WIKI about using advanced installer.  Is this what I need to be looking at or is there any tutorials to get started?

**Comment by jrosetto** [comment]
OK I'm calling it a night.  I missed the fact that I need to compile this with visual studio...  Maybe the 9" netbook I'm on.  I'll jump on the NASA computer tomorrow and look it over again.  Thanks for the 'DUH!'.

**Comment by ahbit** [comment]
Visual Studio to build the bits, and Advanced Installer to make the nice installer from the current project once the bits are built :)

**Comment by jrosetto** [comment]
Well, still having issues.  I tried to compile and when executing the file I get 

INFO : 1/20/2016 7:35:38 AM : Starting up TopPatch Windows Agent 
INFO : 1/20/2016 7:35:38 AM : Retrieving Ip/Hostname from Config file...
INFO : 1/20/2016 7:35:38 AM : Found ip address: 192.168.5.195

Then the program crashes.  Can someone give me a quick rundown of how to get this compiled for testing purposes?
